services:
  wpdb:
    image: mysql:5.7
    platform: linux/x86_64 # M1チップ対応のため追記
    volumes:
      - wpdb_data:/var/lib/mysql
      - ./data/mysql-init:/docker-entrypoint-initdb.d
    restart: on-failure
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    command: mysqld --innodb_use_native_aio=0

  test_db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: "${WORDPRESS_TEST_DB_NAME}"
      MYSQL_USER: "${WORDPRESS_TEST_DB_USER}"
      MYSQL_PASSWORD: "${WORDPRESS_TEST_DB_PASSWORD}"

  wordpress:
    build: .
    platform: linux/x86_64
    volumes:
      - ./:/var/www/html/wp-content/plugins/${PLUGIN_NAME}
      - ./debug.log:/var/www/html/wp-content/debug.log
      - ./data/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
    restart: on-failure
    depends_on:
      - wpdb
    ports:
      - "${WEB_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
      WP_ENV: development # 開発環境の識別用の環境変数

  test_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/x86_64 # M1チップ対応のため追記
    restart: on-failure
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: test_db
      PMA_USER: "${WORDPRESS_TEST_DB_USER}"
      PMA_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    links:
      - test_db
    ports:
      - ${PHPMYADMIN_TEST_PORT}:80
    volumes:
      - ./data/phpmyadmin/test/sessions:/sessions

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/x86_64 # M1チップ対応のため追記
    restart: on-failure
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: wpdb
      PMA_USER: "${WORDPRESS_DB_USER}"
      PMA_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    links:
      - wpdb
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ./data/phpmyadmin/sessions:/sessions

volumes:
  wpdb_data:
  wordpress:
