version: "3.2"
services:
  wpdb:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0
    container_name: "wp_mysql80"
    networks:
      - wordpress000net1
    volumes:
      - wpdb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
  wordpress:
    image: wordpress:latest
    container_name: "wordpress"
    networks:
      - wordpress000net1
    volumes:
      - ./:/var/www/html/wp-content/plugins/ajax-snippets
      - ./themes/cocoon-master:/var/www/html/wp-content/themes/cocoon-master # テーマcocoonを入れる
      # - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - wpdb
    ports:
      - 18085:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: passw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=wpdb #mysqlサービス名を指定
      - PMA_USER=user
      - PMA_PASSWORD=passw0rd
    links:
      - wpdb
    ports:
      - 18885:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

networks:
  wordpress000net1:

volumes:
  wpdb: