version: "3"
services:
  wpdb:
    image: mysql:5.7
    platform: linux/x86_64 # M1チップ対応のため追記
    networks:
      - wordpress000net1
    volumes:
      - wpdb:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    command: mysqld --innodb_use_native_aio=0

  wordpress:
    image: wordpress:latest
    networks:
      - wordpress000net1
    volumes:
      - ./:/var/www/html/wp-content/plugins/ajax-snippets
      - ./themes/cocoon-master:/var/www/html/wp-content/themes/cocoon-master # テーマcocoonを入れる
      # - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - wpdb
    ports:
      - 18088:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: passw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: wpdb
      PMA_USER: user
      PMA_PASSWORD: passw0rd
    networks:
      - wordpress000net1
    links:
      - wpdb
    ports:
      - 18885:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

networks:
  wordpress000net1:

volumes:
  wpdb:
  wordpress: